// Binding snapshot used only when building on docs.rs. Normal builds generate bindings from the
// installed UHD headers in build.rs. Regenerate this file when the wrapped UHD C API changes.

/* automatically generated by rust-bindgen 0.69.5 */

pub mod uhd_error {
    pub type Type = ::std::os::raw::c_uint;
    pub const UHD_ERROR_NONE: Type = 0;
    pub const UHD_ERROR_INVALID_DEVICE: Type = 1;
    pub const UHD_ERROR_INDEX: Type = 10;
    pub const UHD_ERROR_KEY: Type = 11;
    pub const UHD_ERROR_NOT_IMPLEMENTED: Type = 20;
    pub const UHD_ERROR_USB: Type = 21;
    pub const UHD_ERROR_IO: Type = 30;
    pub const UHD_ERROR_OS: Type = 31;
    pub const UHD_ERROR_ASSERTION: Type = 40;
    pub const UHD_ERROR_LOOKUP: Type = 41;
    pub const UHD_ERROR_TYPE: Type = 42;
    pub const UHD_ERROR_VALUE: Type = 43;
    pub const UHD_ERROR_RUNTIME: Type = 44;
    pub const UHD_ERROR_ENVIRONMENT: Type = 45;
    pub const UHD_ERROR_SYSTEM: Type = 46;
    pub const UHD_ERROR_EXCEPT: Type = 47;
    pub const UHD_ERROR_BOOSTEXCEPT: Type = 60;
    pub const UHD_ERROR_STDEXCEPT: Type = 70;
    pub const UHD_ERROR_UNKNOWN: Type = 100;
}
extern "C" {
    pub fn uhd_get_last_error(
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_get_abi_string(
        abi_string_out: *mut ::std::os::raw::c_char,
        buffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_get_version_string(
        version_out: *mut ::std::os::raw::c_char,
        buffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_rx_metadata_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_tx_metadata_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_async_metadata_t {
    _unused: [u8; 0],
}
pub type uhd_rx_metadata_handle = *mut uhd_rx_metadata_t;
pub type uhd_tx_metadata_handle = *mut uhd_tx_metadata_t;
pub type uhd_async_metadata_handle = *mut uhd_async_metadata_t;
pub mod uhd_rx_metadata_error_code_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const UHD_RX_METADATA_ERROR_CODE_NONE: Type = 0;
    pub const UHD_RX_METADATA_ERROR_CODE_TIMEOUT: Type = 1;
    pub const UHD_RX_METADATA_ERROR_CODE_LATE_COMMAND: Type = 2;
    pub const UHD_RX_METADATA_ERROR_CODE_BROKEN_CHAIN: Type = 4;
    pub const UHD_RX_METADATA_ERROR_CODE_OVERFLOW: Type = 8;
    pub const UHD_RX_METADATA_ERROR_CODE_ALIGNMENT: Type = 12;
    pub const UHD_RX_METADATA_ERROR_CODE_BAD_PACKET: Type = 15;
}
extern "C" {
    pub fn uhd_rx_metadata_make(handle: *mut uhd_rx_metadata_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_free(handle: *mut uhd_rx_metadata_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_has_time_spec(
        h: uhd_rx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_time_spec(
        h: uhd_rx_metadata_handle,
        full_secs_out: *mut i64,
        frac_secs_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_more_fragments(
        h: uhd_rx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_fragment_offset(
        h: uhd_rx_metadata_handle,
        fragment_offset_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_start_of_burst(
        h: uhd_rx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_end_of_burst(
        h: uhd_rx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_out_of_sequence(
        h: uhd_rx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_to_pp_string(
        h: uhd_rx_metadata_handle,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_error_code(
        h: uhd_rx_metadata_handle,
        error_code_out: *mut uhd_rx_metadata_error_code_t::Type,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_strerror(
        h: uhd_rx_metadata_handle,
        strerror_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_metadata_last_error(
        h: uhd_rx_metadata_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_metadata_make(
        handle: *mut uhd_tx_metadata_handle,
        has_time_spec: bool,
        full_secs: i64,
        frac_secs: f64,
        start_of_burst: bool,
        end_of_burst: bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_metadata_free(handle: *mut uhd_tx_metadata_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_metadata_has_time_spec(
        h: uhd_tx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_metadata_time_spec(
        h: uhd_tx_metadata_handle,
        full_secs_out: *mut i64,
        frac_secs_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_metadata_start_of_burst(
        h: uhd_tx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_metadata_end_of_burst(
        h: uhd_tx_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_metadata_last_error(
        h: uhd_tx_metadata_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
pub mod uhd_async_metadata_event_code_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const UHD_ASYNC_METADATA_EVENT_CODE_BURST_ACK: Type = 1;
    pub const UHD_ASYNC_METADATA_EVENT_CODE_UNDERFLOW: Type = 2;
    pub const UHD_ASYNC_METADATA_EVENT_CODE_SEQ_ERROR: Type = 4;
    pub const UHD_ASYNC_METADATA_EVENT_CODE_TIME_ERROR: Type = 8;
    pub const UHD_ASYNC_METADATA_EVENT_CODE_UNDERFLOW_IN_PACKET: Type = 16;
    pub const UHD_ASYNC_METADATA_EVENT_CODE_SEQ_ERROR_IN_BURST: Type = 32;
    pub const UHD_ASYNC_METADATA_EVENT_CODE_USER_PAYLOAD: Type = 64;
}
extern "C" {
    pub fn uhd_async_metadata_make(handle: *mut uhd_async_metadata_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_async_metadata_free(handle: *mut uhd_async_metadata_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_async_metadata_channel(
        h: uhd_async_metadata_handle,
        channel_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_async_metadata_has_time_spec(
        h: uhd_async_metadata_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_async_metadata_time_spec(
        h: uhd_async_metadata_handle,
        full_secs_out: *mut i64,
        frac_secs_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_async_metadata_event_code(
        h: uhd_async_metadata_handle,
        event_code_out: *mut uhd_async_metadata_event_code_t::Type,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_async_metadata_user_payload(
        h: uhd_async_metadata_handle,
        user_payload_out: *mut u32,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_async_metadata_last_error(
        h: uhd_async_metadata_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_range_t {
    pub start: f64,
    pub stop: f64,
    pub step: f64,
}
#[test]
fn bindgen_test_layout_uhd_range_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_range_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_range_t>(),
        24usize,
        concat!("Size of: ", stringify!(uhd_range_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_range_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_range_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).start) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_range_t),
            "::",
            stringify!(start)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).stop) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_range_t),
            "::",
            stringify!(stop)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).step) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_range_t),
            "::",
            stringify!(step)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_meta_range_t {
    _unused: [u8; 0],
}
pub type uhd_meta_range_handle = *mut uhd_meta_range_t;
extern "C" {
    pub fn uhd_range_to_pp_string(
        range: *const uhd_range_t,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_make(h: *mut uhd_meta_range_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_free(h: *mut uhd_meta_range_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_start(h: uhd_meta_range_handle, start_out: *mut f64) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_stop(h: uhd_meta_range_handle, stop_out: *mut f64) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_step(h: uhd_meta_range_handle, step_out: *mut f64) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_clip(
        h: uhd_meta_range_handle,
        value: f64,
        clip_step: bool,
        result_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_size(h: uhd_meta_range_handle, size_out: *mut usize) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_push_back(
        h: uhd_meta_range_handle,
        range: *const uhd_range_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_at(
        h: uhd_meta_range_handle,
        num: usize,
        range_out: *mut uhd_range_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_to_pp_string(
        h: uhd_meta_range_handle,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_meta_range_last_error(
        h: uhd_meta_range_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_sensor_value_t {
    _unused: [u8; 0],
}
pub type uhd_sensor_value_handle = *mut uhd_sensor_value_t;
pub mod uhd_sensor_value_data_type_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const UHD_SENSOR_VALUE_BOOLEAN: Type = 98;
    pub const UHD_SENSOR_VALUE_INTEGER: Type = 105;
    pub const UHD_SENSOR_VALUE_REALNUM: Type = 114;
    pub const UHD_SENSOR_VALUE_STRING: Type = 115;
}
extern "C" {
    pub fn uhd_sensor_value_make(h: *mut uhd_sensor_value_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_make_from_bool(
        h: *mut uhd_sensor_value_handle,
        name: *const ::std::os::raw::c_char,
        value: bool,
        utrue: *const ::std::os::raw::c_char,
        ufalse: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_make_from_int(
        h: *mut uhd_sensor_value_handle,
        name: *const ::std::os::raw::c_char,
        value: ::std::os::raw::c_int,
        unit: *const ::std::os::raw::c_char,
        formatter: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_make_from_realnum(
        h: *mut uhd_sensor_value_handle,
        name: *const ::std::os::raw::c_char,
        value: f64,
        unit: *const ::std::os::raw::c_char,
        formatter: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_make_from_string(
        h: *mut uhd_sensor_value_handle,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
        unit: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_free(h: *mut uhd_sensor_value_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_to_bool(
        h: uhd_sensor_value_handle,
        value_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_to_int(
        h: uhd_sensor_value_handle,
        value_out: *mut ::std::os::raw::c_int,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_to_realnum(
        h: uhd_sensor_value_handle,
        value_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_name(
        h: uhd_sensor_value_handle,
        name_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_value(
        h: uhd_sensor_value_handle,
        value_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_unit(
        h: uhd_sensor_value_handle,
        unit_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_data_type(
        h: uhd_sensor_value_handle,
        data_type_out: *mut uhd_sensor_value_data_type_t::Type,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_to_pp_string(
        h: uhd_sensor_value_handle,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_sensor_value_last_error(
        h: uhd_sensor_value_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_string_vector_t {
    _unused: [u8; 0],
}
pub type uhd_string_vector_handle = *mut uhd_string_vector_t;
extern "C" {
    pub fn uhd_string_vector_make(h: *mut uhd_string_vector_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_string_vector_free(h: *mut uhd_string_vector_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_string_vector_push_back(
        h: *mut uhd_string_vector_handle,
        value: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_string_vector_at(
        h: uhd_string_vector_handle,
        index: usize,
        value_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_string_vector_size(
        h: uhd_string_vector_handle,
        size_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_string_vector_last_error(
        h: uhd_string_vector_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
pub mod uhd_tune_request_policy_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const UHD_TUNE_REQUEST_POLICY_NONE: Type = 78;
    pub const UHD_TUNE_REQUEST_POLICY_AUTO: Type = 65;
    pub const UHD_TUNE_REQUEST_POLICY_MANUAL: Type = 77;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_tune_request_t {
    pub target_freq: f64,
    pub rf_freq_policy: uhd_tune_request_policy_t::Type,
    pub rf_freq: f64,
    pub dsp_freq_policy: uhd_tune_request_policy_t::Type,
    pub dsp_freq: f64,
    pub args: *mut ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_uhd_tune_request_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_tune_request_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_tune_request_t>(),
        48usize,
        concat!("Size of: ", stringify!(uhd_tune_request_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_tune_request_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_tune_request_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).target_freq) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_request_t),
            "::",
            stringify!(target_freq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rf_freq_policy) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_request_t),
            "::",
            stringify!(rf_freq_policy)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rf_freq) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_request_t),
            "::",
            stringify!(rf_freq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).dsp_freq_policy) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_request_t),
            "::",
            stringify!(dsp_freq_policy)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).dsp_freq) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_request_t),
            "::",
            stringify!(dsp_freq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).args) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_request_t),
            "::",
            stringify!(args)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_tune_result_t {
    pub clipped_rf_freq: f64,
    pub target_rf_freq: f64,
    pub actual_rf_freq: f64,
    pub target_dsp_freq: f64,
    pub actual_dsp_freq: f64,
}
#[test]
fn bindgen_test_layout_uhd_tune_result_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_tune_result_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_tune_result_t>(),
        40usize,
        concat!("Size of: ", stringify!(uhd_tune_result_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_tune_result_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_tune_result_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).clipped_rf_freq) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_result_t),
            "::",
            stringify!(clipped_rf_freq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).target_rf_freq) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_result_t),
            "::",
            stringify!(target_rf_freq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).actual_rf_freq) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_result_t),
            "::",
            stringify!(actual_rf_freq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).target_dsp_freq) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_result_t),
            "::",
            stringify!(target_dsp_freq)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).actual_dsp_freq) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_tune_result_t),
            "::",
            stringify!(actual_dsp_freq)
        )
    );
}
extern "C" {
    pub fn uhd_tune_result_to_pp_string(
        tune_result: *mut uhd_tune_result_t,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_usrp_rx_info_t {
    pub mboard_id: *mut ::std::os::raw::c_char,
    pub mboard_name: *mut ::std::os::raw::c_char,
    pub mboard_serial: *mut ::std::os::raw::c_char,
    pub rx_id: *mut ::std::os::raw::c_char,
    pub rx_subdev_name: *mut ::std::os::raw::c_char,
    pub rx_subdev_spec: *mut ::std::os::raw::c_char,
    pub rx_serial: *mut ::std::os::raw::c_char,
    pub rx_antenna: *mut ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_uhd_usrp_rx_info_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_usrp_rx_info_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_usrp_rx_info_t>(),
        64usize,
        concat!("Size of: ", stringify!(uhd_usrp_rx_info_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_usrp_rx_info_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_usrp_rx_info_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mboard_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(mboard_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mboard_name) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(mboard_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mboard_serial) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(mboard_serial)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rx_id) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(rx_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rx_subdev_name) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(rx_subdev_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rx_subdev_spec) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(rx_subdev_spec)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rx_serial) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(rx_serial)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).rx_antenna) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_rx_info_t),
            "::",
            stringify!(rx_antenna)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_usrp_tx_info_t {
    pub mboard_id: *mut ::std::os::raw::c_char,
    pub mboard_name: *mut ::std::os::raw::c_char,
    pub mboard_serial: *mut ::std::os::raw::c_char,
    pub tx_id: *mut ::std::os::raw::c_char,
    pub tx_subdev_name: *mut ::std::os::raw::c_char,
    pub tx_subdev_spec: *mut ::std::os::raw::c_char,
    pub tx_serial: *mut ::std::os::raw::c_char,
    pub tx_antenna: *mut ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_uhd_usrp_tx_info_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_usrp_tx_info_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_usrp_tx_info_t>(),
        64usize,
        concat!("Size of: ", stringify!(uhd_usrp_tx_info_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_usrp_tx_info_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_usrp_tx_info_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mboard_id) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(mboard_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mboard_name) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(mboard_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).mboard_serial) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(mboard_serial)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tx_id) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(tx_id)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tx_subdev_name) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(tx_subdev_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tx_subdev_spec) as usize - ptr as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(tx_subdev_spec)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tx_serial) as usize - ptr as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(tx_serial)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).tx_antenna) as usize - ptr as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_usrp_tx_info_t),
            "::",
            stringify!(tx_antenna)
        )
    );
}
extern "C" {
    pub fn uhd_usrp_rx_info_free(rx_info: *mut uhd_usrp_rx_info_t) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_tx_info_free(tx_info: *mut uhd_usrp_tx_info_t) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_dboard_eeprom_t {
    _unused: [u8; 0],
}
pub type uhd_dboard_eeprom_handle = *mut uhd_dboard_eeprom_t;
extern "C" {
    pub fn uhd_dboard_eeprom_make(h: *mut uhd_dboard_eeprom_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_free(h: *mut uhd_dboard_eeprom_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_get_id(
        h: uhd_dboard_eeprom_handle,
        id_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_set_id(
        h: uhd_dboard_eeprom_handle,
        id: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_get_serial(
        h: uhd_dboard_eeprom_handle,
        serial_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_set_serial(
        h: uhd_dboard_eeprom_handle,
        serial: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_get_revision(
        h: uhd_dboard_eeprom_handle,
        revision_out: *mut ::std::os::raw::c_int,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_set_revision(
        h: uhd_dboard_eeprom_handle,
        revision: ::std::os::raw::c_int,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_dboard_eeprom_last_error(
        h: uhd_dboard_eeprom_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_mboard_eeprom_t {
    _unused: [u8; 0],
}
pub type uhd_mboard_eeprom_handle = *mut uhd_mboard_eeprom_t;
extern "C" {
    pub fn uhd_mboard_eeprom_make(h: *mut uhd_mboard_eeprom_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_mboard_eeprom_free(h: *mut uhd_mboard_eeprom_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_mboard_eeprom_get_value(
        h: uhd_mboard_eeprom_handle,
        key: *const ::std::os::raw::c_char,
        value_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_mboard_eeprom_set_value(
        h: uhd_mboard_eeprom_handle,
        key: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_mboard_eeprom_last_error(
        h: uhd_mboard_eeprom_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_subdev_spec_pair_t {
    pub db_name: *mut ::std::os::raw::c_char,
    pub sd_name: *mut ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_uhd_subdev_spec_pair_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_subdev_spec_pair_t> =
        ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_subdev_spec_pair_t>(),
        16usize,
        concat!("Size of: ", stringify!(uhd_subdev_spec_pair_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_subdev_spec_pair_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_subdev_spec_pair_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).db_name) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_subdev_spec_pair_t),
            "::",
            stringify!(db_name)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).sd_name) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_subdev_spec_pair_t),
            "::",
            stringify!(sd_name)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_subdev_spec_t {
    _unused: [u8; 0],
}
pub type uhd_subdev_spec_handle = *mut uhd_subdev_spec_t;
extern "C" {
    pub fn uhd_subdev_spec_pair_free(
        subdev_spec_pair: *mut uhd_subdev_spec_pair_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_pairs_equal(
        first: *const uhd_subdev_spec_pair_t,
        second: *const uhd_subdev_spec_pair_t,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_make(
        h: *mut uhd_subdev_spec_handle,
        markup: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_free(h: *mut uhd_subdev_spec_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_size(h: uhd_subdev_spec_handle, size_out: *mut usize)
        -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_push_back(
        h: uhd_subdev_spec_handle,
        markup: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_at(
        h: uhd_subdev_spec_handle,
        num: usize,
        subdev_spec_pair_out: *mut uhd_subdev_spec_pair_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_to_pp_string(
        h: uhd_subdev_spec_handle,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_to_string(
        h: uhd_subdev_spec_handle,
        string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_subdev_spec_last_error(
        h: uhd_subdev_spec_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_stream_args_t {
    pub cpu_format: *mut ::std::os::raw::c_char,
    pub otw_format: *mut ::std::os::raw::c_char,
    pub args: *mut ::std::os::raw::c_char,
    pub channel_list: *mut usize,
    pub n_channels: ::std::os::raw::c_int,
}
#[test]
fn bindgen_test_layout_uhd_stream_args_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_stream_args_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_stream_args_t>(),
        40usize,
        concat!("Size of: ", stringify!(uhd_stream_args_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_stream_args_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_stream_args_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).cpu_format) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_args_t),
            "::",
            stringify!(cpu_format)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).otw_format) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_args_t),
            "::",
            stringify!(otw_format)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).args) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_args_t),
            "::",
            stringify!(args)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).channel_list) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_args_t),
            "::",
            stringify!(channel_list)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).n_channels) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_args_t),
            "::",
            stringify!(n_channels)
        )
    );
}
pub mod uhd_stream_mode_t {
    pub type Type = ::std::os::raw::c_uint;
    pub const UHD_STREAM_MODE_START_CONTINUOUS: Type = 97;
    pub const UHD_STREAM_MODE_STOP_CONTINUOUS: Type = 111;
    pub const UHD_STREAM_MODE_NUM_SAMPS_AND_DONE: Type = 100;
    pub const UHD_STREAM_MODE_NUM_SAMPS_AND_MORE: Type = 109;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_stream_cmd_t {
    pub stream_mode: uhd_stream_mode_t::Type,
    pub num_samps: usize,
    pub stream_now: bool,
    pub time_spec_full_secs: i64,
    pub time_spec_frac_secs: f64,
}
#[test]
fn bindgen_test_layout_uhd_stream_cmd_t() {
    const UNINIT: ::std::mem::MaybeUninit<uhd_stream_cmd_t> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<uhd_stream_cmd_t>(),
        40usize,
        concat!("Size of: ", stringify!(uhd_stream_cmd_t))
    );
    assert_eq!(
        ::std::mem::align_of::<uhd_stream_cmd_t>(),
        8usize,
        concat!("Alignment of ", stringify!(uhd_stream_cmd_t))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).stream_mode) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_cmd_t),
            "::",
            stringify!(stream_mode)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).num_samps) as usize - ptr as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_cmd_t),
            "::",
            stringify!(num_samps)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).stream_now) as usize - ptr as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_cmd_t),
            "::",
            stringify!(stream_now)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).time_spec_full_secs) as usize - ptr as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_cmd_t),
            "::",
            stringify!(time_spec_full_secs)
        )
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).time_spec_frac_secs) as usize - ptr as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(uhd_stream_cmd_t),
            "::",
            stringify!(time_spec_frac_secs)
        )
    );
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_rx_streamer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_tx_streamer {
    _unused: [u8; 0],
}
pub type uhd_rx_streamer_handle = *mut uhd_rx_streamer;
pub type uhd_tx_streamer_handle = *mut uhd_tx_streamer;
extern "C" {
    pub fn uhd_rx_streamer_make(h: *mut uhd_rx_streamer_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_streamer_free(h: *mut uhd_rx_streamer_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_streamer_num_channels(
        h: uhd_rx_streamer_handle,
        num_channels_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_streamer_max_num_samps(
        h: uhd_rx_streamer_handle,
        max_num_samps_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_streamer_recv(
        h: uhd_rx_streamer_handle,
        buffs: *mut *mut ::std::os::raw::c_void,
        samps_per_buff: usize,
        md: *mut uhd_rx_metadata_handle,
        timeout: f64,
        one_packet: bool,
        items_recvd: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_streamer_issue_stream_cmd(
        h: uhd_rx_streamer_handle,
        stream_cmd: *const uhd_stream_cmd_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_rx_streamer_last_error(
        h: uhd_rx_streamer_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_streamer_make(h: *mut uhd_tx_streamer_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_streamer_free(h: *mut uhd_tx_streamer_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_streamer_num_channels(
        h: uhd_tx_streamer_handle,
        num_channels_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_streamer_max_num_samps(
        h: uhd_tx_streamer_handle,
        max_num_samps_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_streamer_send(
        h: uhd_tx_streamer_handle,
        buffs: *mut *const ::std::os::raw::c_void,
        samps_per_buff: usize,
        md: *mut uhd_tx_metadata_handle,
        timeout: f64,
        items_sent: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_streamer_recv_async_msg(
        h: uhd_tx_streamer_handle,
        md: *mut uhd_async_metadata_handle,
        timeout: f64,
        valid: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_tx_streamer_last_error(
        h: uhd_tx_streamer_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_usrp {
    _unused: [u8; 0],
}
pub type uhd_usrp_handle = *mut uhd_usrp;
extern "C" {
    pub fn uhd_usrp_find(
        args: *const ::std::os::raw::c_char,
        strings_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_make(
        h: *mut uhd_usrp_handle,
        args: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_free(h: *mut uhd_usrp_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_last_error(
        h: uhd_usrp_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_stream(
        h: uhd_usrp_handle,
        stream_args: *mut uhd_stream_args_t,
        h_out: uhd_rx_streamer_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_stream(
        h: uhd_usrp_handle,
        stream_args: *mut uhd_stream_args_t,
        h_out: uhd_tx_streamer_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_info(
        h: uhd_usrp_handle,
        chan: usize,
        info_out: *mut uhd_usrp_rx_info_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_info(
        h: uhd_usrp_handle,
        chan: usize,
        info_out: *mut uhd_usrp_tx_info_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_master_clock_rate(
        h: uhd_usrp_handle,
        rate: f64,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_master_clock_rate(
        h: uhd_usrp_handle,
        mboard: usize,
        clock_rate_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_pp_string(
        h: uhd_usrp_handle,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_mboard_name(
        h: uhd_usrp_handle,
        mboard: usize,
        mboard_name_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_time_now(
        h: uhd_usrp_handle,
        mboard: usize,
        full_secs_out: *mut i64,
        frac_secs_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_time_last_pps(
        h: uhd_usrp_handle,
        mboard: usize,
        full_secs_out: *mut i64,
        frac_secs_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_time_now(
        h: uhd_usrp_handle,
        full_secs: i64,
        frac_secs: f64,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_time_next_pps(
        h: uhd_usrp_handle,
        full_secs: i64,
        frac_secs: f64,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_time_unknown_pps(
        h: uhd_usrp_handle,
        full_secs: i64,
        frac_secs: f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_time_synchronized(
        h: uhd_usrp_handle,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_command_time(
        h: uhd_usrp_handle,
        full_secs: i64,
        frac_secs: f64,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clear_command_time(h: uhd_usrp_handle, mboard: usize) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_time_source(
        h: uhd_usrp_handle,
        time_source: *const ::std::os::raw::c_char,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_time_source(
        h: uhd_usrp_handle,
        mboard: usize,
        time_source_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_time_sources(
        h: uhd_usrp_handle,
        mboard: usize,
        time_sources_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_clock_source(
        h: uhd_usrp_handle,
        clock_source: *const ::std::os::raw::c_char,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_clock_source(
        h: uhd_usrp_handle,
        mboard: usize,
        clock_source_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_clock_sources(
        h: uhd_usrp_handle,
        mboard: usize,
        clock_sources_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_clock_source_out(
        h: uhd_usrp_handle,
        enb: bool,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_time_source_out(
        h: uhd_usrp_handle,
        enb: bool,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_num_mboards(
        h: uhd_usrp_handle,
        num_mboards_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_mboard_sensor(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        mboard: usize,
        sensor_value_out: *mut uhd_sensor_value_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_mboard_sensor_names(
        h: uhd_usrp_handle,
        mboard: usize,
        mboard_sensor_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_user_register(
        h: uhd_usrp_handle,
        addr: u8,
        data: u32,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_mboard_eeprom(
        h: uhd_usrp_handle,
        mb_eeprom: uhd_mboard_eeprom_handle,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_mboard_eeprom(
        h: uhd_usrp_handle,
        mb_eeprom: uhd_mboard_eeprom_handle,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_dboard_eeprom(
        h: uhd_usrp_handle,
        db_eeprom: uhd_dboard_eeprom_handle,
        unit: *const ::std::os::raw::c_char,
        slot: *const ::std::os::raw::c_char,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_dboard_eeprom(
        h: uhd_usrp_handle,
        db_eeprom: uhd_dboard_eeprom_handle,
        unit: *const ::std::os::raw::c_char,
        slot: *const ::std::os::raw::c_char,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_subdev_spec(
        h: uhd_usrp_handle,
        subdev_spec: uhd_subdev_spec_handle,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_subdev_spec(
        h: uhd_usrp_handle,
        mboard: usize,
        subdev_spec_out: uhd_subdev_spec_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_num_channels(
        h: uhd_usrp_handle,
        num_channels_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_subdev_name(
        h: uhd_usrp_handle,
        chan: usize,
        rx_subdev_name_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_rate(h: uhd_usrp_handle, rate: f64, chan: usize) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_rate(
        h: uhd_usrp_handle,
        chan: usize,
        rate_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_rates(
        h: uhd_usrp_handle,
        chan: usize,
        rates_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_freq(
        h: uhd_usrp_handle,
        tune_request: *mut uhd_tune_request_t,
        chan: usize,
        tune_result: *mut uhd_tune_result_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_freq(
        h: uhd_usrp_handle,
        chan: usize,
        freq_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_freq_range(
        h: uhd_usrp_handle,
        chan: usize,
        freq_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_fe_rx_freq_range(
        h: uhd_usrp_handle,
        chan: usize,
        freq_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_lo_names(
        h: uhd_usrp_handle,
        chan: usize,
        rx_lo_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_lo_source(
        h: uhd_usrp_handle,
        src: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_lo_source(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        rx_lo_source_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_lo_sources(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        rx_lo_sources_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_lo_export_enabled(
        h: uhd_usrp_handle,
        enabled: bool,
        name: *const ::std::os::raw::c_char,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_lo_export_enabled(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_lo_freq(
        h: uhd_usrp_handle,
        freq: f64,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        coerced_freq_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_lo_freq(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        rx_lo_freq_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_gain(
        h: uhd_usrp_handle,
        gain: f64,
        chan: usize,
        gain_name: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_normalized_rx_gain(
        h: uhd_usrp_handle,
        gain: f64,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_agc(h: uhd_usrp_handle, enable: bool, chan: usize) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_gain(
        h: uhd_usrp_handle,
        chan: usize,
        gain_name: *const ::std::os::raw::c_char,
        gain_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_normalized_rx_gain(
        h: uhd_usrp_handle,
        chan: usize,
        gain_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_gain_range(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        gain_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_gain_names(
        h: uhd_usrp_handle,
        chan: usize,
        gain_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_antenna(
        h: uhd_usrp_handle,
        ant: *const ::std::os::raw::c_char,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_antenna(
        h: uhd_usrp_handle,
        chan: usize,
        ant_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_antennas(
        h: uhd_usrp_handle,
        chan: usize,
        antennas_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_sensor_names(
        h: uhd_usrp_handle,
        chan: usize,
        sensor_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_bandwidth(
        h: uhd_usrp_handle,
        bandwidth: f64,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_bandwidth(
        h: uhd_usrp_handle,
        chan: usize,
        bandwidth_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_bandwidth_range(
        h: uhd_usrp_handle,
        chan: usize,
        bandwidth_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_rx_sensor(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        sensor_value_out: *mut uhd_sensor_value_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_dc_offset_enabled(
        h: uhd_usrp_handle,
        enb: bool,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_rx_iq_balance_enabled(
        h: uhd_usrp_handle,
        enb: bool,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_subdev_spec(
        h: uhd_usrp_handle,
        subdev_spec: uhd_subdev_spec_handle,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_subdev_spec(
        h: uhd_usrp_handle,
        mboard: usize,
        subdev_spec_out: uhd_subdev_spec_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_num_channels(
        h: uhd_usrp_handle,
        num_channels_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_subdev_name(
        h: uhd_usrp_handle,
        chan: usize,
        tx_subdev_name_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_rate(h: uhd_usrp_handle, rate: f64, chan: usize) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_rate(
        h: uhd_usrp_handle,
        chan: usize,
        rate_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_rates(
        h: uhd_usrp_handle,
        chan: usize,
        rates_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_freq(
        h: uhd_usrp_handle,
        tune_request: *mut uhd_tune_request_t,
        chan: usize,
        tune_result: *mut uhd_tune_result_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_freq(
        h: uhd_usrp_handle,
        chan: usize,
        freq_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_freq_range(
        h: uhd_usrp_handle,
        chan: usize,
        freq_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_fe_tx_freq_range(
        h: uhd_usrp_handle,
        chan: usize,
        freq_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_lo_names(
        h: uhd_usrp_handle,
        chan: usize,
        tx_lo_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_lo_source(
        h: uhd_usrp_handle,
        src: *const ::std::os::raw::c_char,
        name: *const ::std::os::raw::c_char,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_lo_source(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        tx_lo_source_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_lo_sources(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        tx_lo_sources_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_lo_export_enabled(
        h: uhd_usrp_handle,
        enabled: bool,
        name: *const ::std::os::raw::c_char,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_lo_export_enabled(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        result_out: *mut bool,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_lo_freq(
        h: uhd_usrp_handle,
        freq: f64,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        coerced_freq_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_lo_freq(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        tx_lo_freq_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_gain(
        h: uhd_usrp_handle,
        gain: f64,
        chan: usize,
        gain_name: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_normalized_tx_gain(
        h: uhd_usrp_handle,
        gain: f64,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_gain_range(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        gain_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_gain(
        h: uhd_usrp_handle,
        chan: usize,
        gain_name: *const ::std::os::raw::c_char,
        gain_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_normalized_tx_gain(
        h: uhd_usrp_handle,
        chan: usize,
        gain_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_gain_names(
        h: uhd_usrp_handle,
        chan: usize,
        gain_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_antenna(
        h: uhd_usrp_handle,
        ant: *const ::std::os::raw::c_char,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_antenna(
        h: uhd_usrp_handle,
        chan: usize,
        ant_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_antennas(
        h: uhd_usrp_handle,
        chan: usize,
        antennas_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_tx_bandwidth(
        h: uhd_usrp_handle,
        bandwidth: f64,
        chan: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_bandwidth(
        h: uhd_usrp_handle,
        chan: usize,
        bandwidth_out: *mut f64,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_bandwidth_range(
        h: uhd_usrp_handle,
        chan: usize,
        bandwidth_range_out: uhd_meta_range_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_sensor(
        h: uhd_usrp_handle,
        name: *const ::std::os::raw::c_char,
        chan: usize,
        sensor_value_out: *mut uhd_sensor_value_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_tx_sensor_names(
        h: uhd_usrp_handle,
        chan: usize,
        sensor_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_gpio_banks(
        h: uhd_usrp_handle,
        mboard: usize,
        gpio_banks_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_set_gpio_attr(
        h: uhd_usrp_handle,
        bank: *const ::std::os::raw::c_char,
        attr: *const ::std::os::raw::c_char,
        value: u32,
        mask: u32,
        mboard: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_get_gpio_attr(
        h: uhd_usrp_handle,
        bank: *const ::std::os::raw::c_char,
        attr: *const ::std::os::raw::c_char,
        mboard: usize,
        attr_out: *mut u32,
    ) -> uhd_error::Type;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct uhd_usrp_clock {
    _unused: [u8; 0],
}
pub type uhd_usrp_clock_handle = *mut uhd_usrp_clock;
extern "C" {
    pub fn uhd_usrp_clock_find(
        args: *const ::std::os::raw::c_char,
        devices_out: *mut uhd_string_vector_t,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_make(
        h: *mut uhd_usrp_clock_handle,
        args: *const ::std::os::raw::c_char,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_free(h: *mut uhd_usrp_clock_handle) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_last_error(
        h: uhd_usrp_clock_handle,
        error_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_get_pp_string(
        h: uhd_usrp_clock_handle,
        pp_string_out: *mut ::std::os::raw::c_char,
        strbuffer_len: usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_get_num_boards(
        h: uhd_usrp_clock_handle,
        num_boards_out: *mut usize,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_get_time(
        h: uhd_usrp_clock_handle,
        board: usize,
        clock_time_out: *mut u32,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_get_sensor(
        h: uhd_usrp_clock_handle,
        name: *const ::std::os::raw::c_char,
        board: usize,
        sensor_value_out: *mut uhd_sensor_value_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_usrp_clock_get_sensor_names(
        h: uhd_usrp_clock_handle,
        board: usize,
        sensor_names_out: *mut uhd_string_vector_handle,
    ) -> uhd_error::Type;
}
extern "C" {
    pub fn uhd_set_thread_priority(priority: f32, realtime: bool) -> uhd_error::Type;
}
